In [37]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1,inplace=True)

In [6]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [7]:
le=LabelEncoder()
df['Geography']=le.fit_transform(df['Geography'])
df['Gender']=le.fit_transform(df['Gender'])

In [8]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [9]:
x=df.drop(['Exited'], axis=1)
y=df['Exited']

In [10]:
s=StandardScaler()
x=s.fit_transform(df)

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [18]:
classifier=Sequential()

In [19]:
classifier.add(Dense(activation="relu", input_dim=10, units=6, kernel_initializer="uniform"))

In [20]:
classifier.add(Dense(activation="relu",  units=6, kernel_initializer="uniform"))

In [21]:
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

In [22]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

In [23]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 66        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 115
Trainable params: 115
Non-trainable params: 0
_________________________________________________________________


In [27]:
classifier.fit(x_train,y_train, epochs=50, batch_size=10)

Epoch 1/50
700/700 [==============================] - 2s 2ms/step - loss: 0.5029 - accuracy: 0.7989
Epoch 2/50
700/700 [==============================] - 2s 2ms/step - loss: 0.4994 - accuracy: 0.7989
Epoch 3/50
700/700 [==============================] - 2s 2ms/step - loss: 0.4988 - accuracy: 0.7989
Epoch 4/50
700/700 [==============================] - 2s 2ms/step - loss: 0.5019 - accuracy: 0.7989
Epoch 5/50
700/700 [==============================] - 2s 2ms/step - loss: 0.5020 - accuracy: 0.7989
Epoch 6/50
700/700 [==============================] - 2s 2ms/step - loss: 0.5019 - accuracy: 0.7989
Epoch 7/50
700/700 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7989
Epoch 8/50
700/700 [==============================] - 2s 3ms/step - loss: 0.5022 - accuracy: 0.7989
Epoch 9/50
700/700 [==============================] - 2s 3ms/step - loss: 0.5019 - accuracy: 0.7989
Epoch 10/50
700/700 [==============================] - 2s 2ms/step - loss: 0.5020 - accuracy: 0.7989

In [28]:
y_pred=classifier.predict(x_test)

94/94 [==============================] - 0s 871us/step


In [29]:
y_pred

array([[0.20876904],
       [0.19107607],
       [0.19107607],
       ...,
       [0.20876904],
       [0.20876904],
       [0.19107607]], dtype=float32)

In [39]:
y_pred=np.where(y_pred<0.5,0,1)
y_pred       

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      2371
           1       0.00      0.00      0.00       629

    accuracy                           0.79      3000
   macro avg       0.40      0.50      0.44      3000
weighted avg       0.62      0.79      0.70      3000



C:\Users\meenu\anaconda32\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\meenu\anaconda32\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\meenu\anaconda32\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [42]:
print(confusion_matrix(y_test,y_pred))

[[2371    0]
 [ 629    0]]
